package eventos;

import eventos.Entrada;
import eventos.EventoAbierto;
import eventos.EventoCerrado;
import eventos.Locacion;
import eventos.Usuario;
import eventos.UsuarioFree;
import repositorio.RepositorioLocaciones;
import repositorio.RepositorioServicios;
import repositorio.RepositorioUsuarios;

/* @Accessors
 */public abstract class FixtureTest {
  private EventoCerrado reunionGrande;
  
  private EventoCerrado reunionChica;
  
  private EventoCerrado otroEvento;
  
  private Locacion salon_SM;
  
  private Locacion salon_2;
  
  private Locacion salon_3;
  
  private Locacion salon_Incompleto;
  
  private Usuario usuario1;
  
  private Usuario usuario2;
  
  private Usuario usuario3;
  
  private UsuarioFree usuarioFree;
  
  private Usuario unUsuario;
  
  private EventoCerrado primerEvento;
  
  private EventoCerrado segundoEvento;
  
  private EventoCerrado tercerEvento;
  
  private EventoCerrado cuartoEvento;
  
  private EventoCerrado quintoEvento;
  
  private EventoCerrado eventoPrueba;
  
  private EventoAbierto reunionAbierta;
  
  private EventoAbierto cumple;
  
  private Entrada entradaPrueba;
  
  private RepositorioLocaciones repoLocacion;
  
  private RepositorioServicios repoServicio;
  
  private RepositorioUsuarios repoUsuario;
  
  private int cantMaxDeEventos = 20;
  
  private int contador;
  
  /* @Before
   */public void init() {
    throw new Error("Unresolved compilation problems:"
      + "\n=> cannot be resolved."
      + "\nThe method nombre(java.lang.String) is undefined"
      + "\nThe method punto(Object) is undefined"
      + "\nPoint cannot be resolved."
      + "\nThe method superficie(int) is undefined"
      + "\n=> cannot be resolved."
      + "\nThe method nombre(java.lang.String) is undefined"
      + "\nThe method punto(Object) is undefined"
      + "\nPoint cannot be resolved."
      + "\nThe method superficie(int) is undefined"
      + "\n=> cannot be resolved."
      + "\nThe method nombre(java.lang.String) is undefined"
      + "\nThe method punto(Object) is undefined"
      + "\nPoint cannot be resolved."
      + "\nThe method superficie(int) is undefined"
      + "\n=> cannot be resolved."
      + "\nThe method nombre(java.lang.String) is undefined"
      + "\nThe method superficie(int) is undefined"
      + "\n=> cannot be resolved."
      + "\nThe method nombreUsuario(java.lang.String) is undefined"
      + "\nThe method email(java.lang.String) is undefined"
      + "\nThe method nombreApellido(java.lang.String) is undefined"
      + "\nThe method fechaNacimiento(Object) is undefined"
      + "\nThe method or field LocalDate is undefined"
      + "\nThe method coordenadas(Object) is undefined"
      + "\nPoint cannot be resolved."
      + "\n=> cannot be resolved."
      + "\nThe method nombreUsuario(java.lang.String) is undefined"
      + "\nThe method email(java.lang.String) is undefined"
      + "\nThe method nombreApellido(java.lang.String) is undefined"
      + "\nThe method fechaNacimiento(Object) is undefined"
      + "\nThe method or field LocalDate is undefined"
      + "\nThe method coordenadas(Object) is undefined"
      + "\nPoint cannot be resolved."
      + "\n=> cannot be resolved."
      + "\nThe method email(java.lang.String) is undefined"
      + "\nThe method nombreApellido(java.lang.String) is undefined"
      + "\nThe method fechaNacimiento(Object) is undefined"
      + "\nThe method or field LocalDate is undefined"
      + "\nThe method coordenadas(Object) is undefined"
      + "\nPoint cannot be resolved."
      + "\nThe method esAntisocial(boolean) is undefined"
      + "\n=> cannot be resolved."
      + "\nThe method nombre(java.lang.String) is undefined"
      + "\nThe method organizador(Usuario) is undefined"
      + "\nThe method locacion(Locacion) is undefined"
      + "\nThe method fechaDeInicio(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaFinalizacion(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaLimiteConfirmacion(Object) is undefined"
      + "\nThe method or field LocalDate is undefined"
      + "\nThe method or field Period is undefined"
      + "\n=> cannot be resolved."
      + "\nThe method organizador(Usuario) is undefined"
      + "\nThe method locacion(Locacion) is undefined"
      + "\nThe method fechaDeInicio(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaFinalizacion(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaLimiteConfirmacion(Object) is undefined"
      + "\nThe method or field LocalDate is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method edadMinima(int) is undefined"
      + "\nThe method precioEntrada(int) is undefined"
      + "\n=> cannot be resolved."
      + "\nThe method nombre(java.lang.String) is undefined"
      + "\nThe method organizador(Usuario) is undefined"
      + "\nThe method locacion(Locacion) is undefined"
      + "\nThe method fechaDeInicio(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaFinalizacion(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaLimiteConfirmacion(Object) is undefined"
      + "\nThe method or field LocalDate is undefined"
      + "\nThe method capacidadMaxima(int) is undefined"
      + "\n=> cannot be resolved."
      + "\nThe method nombre(java.lang.String) is undefined"
      + "\nThe method organizador(Usuario) is undefined"
      + "\nThe method locacion(Locacion) is undefined"
      + "\nThe method fechaDeInicio(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\n- cannot be resolved."
      + "\nThe method fechaFinalizacion(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaLimiteConfirmacion(Object) is undefined"
      + "\nThe method or field LocalDate is undefined"
      + "\nThe method or field Period is undefined"
      + "\n- cannot be resolved."
      + "\nThe method capacidadMaxima(int) is undefined"
      + "\n=> cannot be resolved."
      + "\nThe method nombre(java.lang.String) is undefined"
      + "\nThe method organizador(Usuario) is undefined"
      + "\nThe method locacion(Locacion) is undefined"
      + "\nThe method fechaDeInicio(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaFinalizacion(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaLimiteConfirmacion(Object) is undefined"
      + "\nThe method or field LocalDate is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method capacidadMaxima(int) is undefined"
      + "\n=> cannot be resolved."
      + "\nThe method nombreUsuario(java.lang.String) is undefined"
      + "\nThe method fechaNacimiento(Object) is undefined"
      + "\nThe method or field LocalDate is undefined"
      + "\nThe method coordenadas(Object) is undefined"
      + "\nPoint cannot be resolved."
      + "\n=> cannot be resolved."
      + "\nThe method nombre(java.lang.String) is undefined"
      + "\nThe method organizador(Usuario) is undefined"
      + "\nThe method locacion(Locacion) is undefined"
      + "\nThe method fechaDeInicio(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaFinalizacion(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaLimiteConfirmacion(Object) is undefined"
      + "\nThe method or field LocalDate is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method capacidadMaxima(int) is undefined"
      + "\n=> cannot be resolved."
      + "\nThe method nombre(java.lang.String) is undefined"
      + "\nThe method organizador(Usuario) is undefined"
      + "\nThe method locacion(Locacion) is undefined"
      + "\nThe method fechaDeInicio(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaFinalizacion(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaLimiteConfirmacion(Object) is undefined"
      + "\nThe method or field LocalDate is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method capacidadMaxima(int) is undefined"
      + "\n=> cannot be resolved."
      + "\nThe method nombre(java.lang.String) is undefined"
      + "\nThe method organizador(Usuario) is undefined"
      + "\nThe method locacion(Locacion) is undefined"
      + "\nThe method fechaDeInicio(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaFinalizacion(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaLimiteConfirmacion(Object) is undefined"
      + "\nThe method or field LocalDate is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method capacidadMaxima(int) is undefined"
      + "\n=> cannot be resolved."
      + "\nThe method nombre(java.lang.String) is undefined"
      + "\nThe method locacion(Locacion) is undefined"
      + "\nThe method fechaDeInicio(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaFinalizacion(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaLimiteConfirmacion(Object) is undefined"
      + "\nThe method or field LocalDate is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method capacidadMaxima(int) is undefined"
      + "\n=> cannot be resolved."
      + "\nThe method nombre(java.lang.String) is undefined"
      + "\nThe method organizador(Usuario) is undefined"
      + "\nThe method locacion(Locacion) is undefined"
      + "\nThe method fechaDeInicio(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaFinalizacion(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaLimiteConfirmacion(Object) is undefined"
      + "\nThe method or field LocalDate is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method capacidadMaxima(int) is undefined"
      + "\n=> cannot be resolved."
      + "\nThe method nombre(java.lang.String) is undefined"
      + "\nThe method locacion(Locacion) is undefined"
      + "\nThe method fechaDeInicio(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaFinalizacion(Object) is undefined"
      + "\nThe method or field LocalDateTime is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method fechaLimiteConfirmacion(Object) is undefined"
      + "\nThe method or field LocalDate is undefined"
      + "\nThe method or field Period is undefined"
      + "\nThe method capacidadMaxima(int) is undefined"
      + "\nof cannot be resolved"
      + "\nof cannot be resolved"
      + "\nof cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nof cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved"
      + "\nnow cannot be resolved"
      + "\nplus cannot be resolved"
      + "\nofDays cannot be resolved");
  }
}
